### ISSUE TITLE
Exported samples missing labeled elements

### ISSUE THREAD

**Issue by reuben** [mozilla-applied-ml/fta#68] opened 2020-11-12 12:22 UTC
All of these are affected:

```python
In [10]: from bs4 import BeautifulSoup as BS
    ...: for root, dirnames, filenames in os.walk("2020-11-11-3e2954"):
    ...:     for filename in fnmatch.filter(filenames, "*.html"):
    ...:         with open(os.path.join(root, filename)) as fin:
    ...:             soup = BS(fin.read())
    ...:         if not soup.find_all(lambda tag: tag.has_attr("data-fta_id")):
    ...:             print("no labels in {}".format(filename))
    ...:
    ...:
    ...:
no labels in 39.n.html
no labels in 188.html
no labels in 106.html
no labels in 145.html
no labels in 187.html
no labels in 172.html
no labels in 174.html
no labels in 16.html
no labels in 9.html
no labels in 171.html
no labels in 121.html
no labels in 173.n.html
```

Sample 39 for example does have a labeled element in the production deploy, but not in the export, and it's tagged as `.n.html`. All the other samples in the list above have labeled elements in the production deploy but not in the export, and weirdly only some of them get tagged as `.n.html`.

**Comment by birdsarah** [comment] 2020-11-12 21:23
Thank you for this roundup.

**Comment by birdsarah** [comment] 2020-11-13 07:14
Sorry this isn't obvious but I think you've confused the labeled_sample id - which is the ids in the above file names and the original sample id, which is the id you see in the, url when you're labeling a sample.

The two no label outputs are correct:
* [labeled_sampled 39](/admin/samples/labeledsample/39/change/) is [sample 18](/label/18)
* [labeled_sample 173](/admin/samples/labeledsample/173/change/) is [sample 76](/label/76) 

For the remaining, the results are:
* LS 188 -- S62 -- https://www.espn.com/
* LS 106 -- S129 -- https://mail.qq.com/
* LS 145 -- S131 -- https://www.businessinsider.com/subscription/prime
* LS 187 -- S30 -- https://www.espn.com/
* LS 172 -- S136 -- https://www.tiktok.com/
* LS 174 -- S91 -- https://www.tiktok.com/
* LS 16 -- S177 -- https://account.alibabacloud.com/register/intl_reg
* LS 9 -- S162 -- https://www.reddit.com/
* LS 171 -- S70 -- https://soundcloud.com/
* LS 121 -- S134 -- https://account.alibabacloud.com/login/login.htm?o

These are all cases where there are entries in the database for LabeledElements. But when you load the labeling view, the labels aren't displayed. This is because there's no data-fta-id elements in the LabeledSample modified source meaning that something's going wrong with the picker.

I've removed the LabeledElements that relate to these Samples from the database.

We will need to fix the picker to fix them.

**Comment by birdsarah** [comment] 2020-11-13 07:15
To avoid this confusion in the future, we should tweak the export code to be the original sample id, so this is easier to track down.

**Comment by birdsarah** [comment] 2020-11-13 07:40
As an aside I noticed that the espn samples are trying to load code. which they shouldn't be.

**Comment by reuben** [comment] 2020-11-16 09:07
> As an aside I noticed that the espn samples are trying to load code. which they shouldn't be.

I couldn't reproduce this.

**Comment by birdsarah** [comment] 2020-11-17 17:19
> I couldn't reproduce this.

Opened #70 to discuss.

**Comment by birdsarah** [comment] 2020-11-17 17:19
Can we close this?

**Comment by birdsarah** [comment] 2020-11-17 17:20
I confirmed things are working as expected now. Will relabel and re-export.

**Closed as completed** 2020-11-17 17:20 UTC
